#!/usr/bin/env python3

import os
import subprocess
from pathlib import Path
from PIL import Image

folder = '/home/eddy/rename/'
output = folder + 'resize/'
maxHeight = 2500

for file in os.scandir(folder):
    if file.path.endswith('.jpg') or file.path.endswith('.jpeg') or file.path.endswith('.png') and file.is_file():
        #print(file.path)
        im = Image.open(file.path)
        _, h = im.size
        outputFile = output + file.name
        if h > maxHeight:
            #print(outputFile)
            subprocess.run(['convert', '-verbose', '-resize', f'x{maxHeight}', file.path, outputFile])
            os.remove(file.path)
        else:
            os.rename(file.path, outputFile)
            Path(outputFile).touch()